---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"

- name: Ensure Kibana is started and enabled at boot.
  systemd:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"
    daemon_reload: yes

- name: Create Directories
  file:
    path: "{{ lookup('vars', kibana_path_item) }}"
    state: directory
    owner: '{{ kibana_user }}'
    group: '{{ kibana_group }}'
    recurse: false
  loop:
    - kibana_log_dir
    - kibana_conf_dir
    - kibana_pid_dir
  loop_control:
    loop_var: kibana_path_item

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
